# Generated by Django 4.1.3 on 2022-11-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="dead",
            field=models.DateField(blank=True, help_text="Fecha de deceso", null=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="phrase",
            field=models.TextField(blank=True, help_text="Frases célebres", null=True),
        ),
    ]
