# Generated by Django 4.1.3 on 2022-11-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0002_alter_director_dead_alter_director_phrase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("famous_phrase", models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="director",
            name="phrase",
            field=models.ForeignKey(
                blank=True,
                help_text="Frase famosa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="miapp.phrase",
            ),
        ),
    ]
