# Generated by Django 4.1.3 on 2022-11-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "short_description",
                    models.CharField(max_length=100, verbose_name="Resumen"),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Descripción"
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Cantidad")),
            ],
        ),
    ]
