# Generated by Django 4.1.3 on 2022-11-28 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_until",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
